// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AssertCard: typeof import('./src/components/AssertCard.vue')['default']
    Assertions: typeof import('./src/components/Assertions.vue')['default']
    BioSuspenseWrapper: typeof import('./src/components/BioSuspenseWrapper.vue')['default']
    Button: typeof import('./src/components/Button.vue')['default']
    CopySpeechBubble: typeof import('./src/components/CopySpeechBubble.vue')['default']
    DashboardHeader: typeof import('./src/components/DashboardHeader.vue')['default']
    EllipsisSpinner: typeof import('./src/components/EllipsisSpinner.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    FullScreenOverlay: typeof import('./src/components/FullScreenOverlay.vue')['default']
    Heading: typeof import('./src/components/Heading.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ImageContainer: typeof import('./src/components/ImageContainer.vue')['default']
    ImageUpload: typeof import('./src/components/ImageUpload.vue')['default']
    Input: typeof import('./src/components/Input.vue')['default']
    Link: typeof import('./src/components/Link.vue')['default']
    NavigationBar: typeof import('./src/components/NavigationBar.vue')['default']
    PopupFullscreen: typeof import('./src/components/PopupFullscreen.vue')['default']
    PopupOverlay: typeof import('./src/components/PopupOverlay.vue')['default']
    RecentPosts: typeof import('./src/components/RecentPosts.vue')['default']
    Route: typeof import('./src/components/Route.vue')['default']
    SectionBody: typeof import('./src/components/SectionBody.vue')['default']
    ShortBio: typeof import('./src/components/ShortBio.vue')['default']
    ShortBioCardDesktop: typeof import('./src/components/ShortBioCardDesktop.vue')['default']
    ShortBioSuspenseWrapper: typeof import('./src/components/ShortBioSuspenseWrapper.vue')['default']
    SmallText: typeof import('./src/components/SmallText.vue')['default']
    SpeechBubble: typeof import('./src/components/SpeechBubble.vue')['default']
    SubHeading: typeof import('./src/components/SubHeading.vue')['default']
    Suspense: typeof import('./src/components/Suspense.vue')['default']
    SuspenseWrapper: typeof import('./src/components/SuspenseWrapper.vue')['default']
    Table: typeof import('./src/components/Table.vue')['default']
    Text: typeof import('./src/components/Text.vue')['default']
    Title: typeof import('./src/components/Title.vue')['default']
    UpdateUserProfile: typeof import('./src/components/UpdateUserProfile.vue')['default']
    VariadicTextSize: typeof import('./src/components/VariadicTextSize.vue')['default']
    WorkHistory: typeof import('./src/components/WorkHistory.vue')['default']
  }
}

export { }
