// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Link: typeof import('./src/components/Link.vue')['default']
    NavigationBar: typeof import('./src/components/NavigationBar.vue')['default']
    RecentPosts: typeof import('./src/components/RecentPosts.vue')['default']
    Route: typeof import('./src/components/Route.vue')['default']
    ShortBio: typeof import('./src/components/ShortBio.vue')['default']
    Title: typeof import('./src/components/Title.vue')['default']
  }
}

export { }
