// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ArticleContainer: typeof import('./src/components/ArticleContainer.vue')['default']
    ArticleList: typeof import('./src/components/ArticleList.vue')['default']
    AssertCard: typeof import('./src/components/AssertCard.vue')['default']
    Assertions: typeof import('./src/components/Assertions.vue')['default']
    BackButton: typeof import('./src/components/BackButton.vue')['default']
    Button: typeof import('./src/components/Button.vue')['default']
    CalendarIcon: typeof import('./src/components/CalendarIcon.vue')['default']
    ChevronRightBtn: typeof import('./src/components/ChevronRightBtn.vue')['default']
    ConfirmDialog: typeof import('./src/components/ConfirmDialog.vue')['default']
    CopySpeechBubble: typeof import('./src/components/CopySpeechBubble.vue')['default']
    DashboardHeader: typeof import('./src/components/DashboardHeader.vue')['default']
    DisplayArticle: typeof import('./src/components/DisplayArticle.vue')['default']
    DisplayProject: typeof import('./src/components/DisplayProject.vue')['default']
    EditArticleForm: typeof import('./src/components/EditArticleForm.vue')['default']
    EditProjectForm: typeof import('./src/components/EditProjectForm.vue')['default']
    EllipsisSpinner: typeof import('./src/components/EllipsisSpinner.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    FullScreenOverlay: typeof import('./src/components/FullScreenOverlay.vue')['default']
    Heading: typeof import('./src/components/Heading.vue')['default']
    ImageContainer: typeof import('./src/components/ImageContainer.vue')['default']
    ImageList: typeof import('./src/components/ImageList.vue')['default']
    ImageUpload: typeof import('./src/components/ImageUpload.vue')['default']
    Input: typeof import('./src/components/Input.vue')['default']
    NavigationBar: typeof import('./src/components/NavigationBar.vue')['default']
    PersonIcon: typeof import('./src/components/PersonIcon.vue')['default']
    PopupOverlay: typeof import('./src/components/PopupOverlay.vue')['default']
    ProjectContainer: typeof import('./src/components/ProjectContainer.vue')['default']
    ProjectList: typeof import('./src/components/ProjectList.vue')['default']
    RecentPosts: typeof import('./src/components/RecentPosts.vue')['default']
    Route: typeof import('./src/components/Route.vue')['default']
    SectionBody: typeof import('./src/components/SectionBody.vue')['default']
    ShortBio: typeof import('./src/components/ShortBio.vue')['default']
    SmallText: typeof import('./src/components/SmallText.vue')['default']
    SubHeading: typeof import('./src/components/SubHeading.vue')['default']
    SuspenseWrapper: typeof import('./src/components/SuspenseWrapper.vue')['default']
    Table: typeof import('./src/components/Table.vue')['default']
    TagList: typeof import('./src/components/TagList.vue')['default']
    Text: typeof import('./src/components/Text.vue')['default']
    Title: typeof import('./src/components/Title.vue')['default']
    UpdateUserProfile: typeof import('./src/components/UpdateUserProfile.vue')['default']
    VariadicTextSize: typeof import('./src/components/VariadicTextSize.vue')['default']
    WorkHistory: typeof import('./src/components/WorkHistory.vue')['default']
    WowSuchEmpty: typeof import('./src/components/WowSuchEmpty.vue')['default']
  }
}

export { }
